### ISSUE TITLE
subprocess OverflowError: long too big to convert

### ISSUE THREAD

**Issue by pintokoaji** [leal26/AeroPy#14]
Hi, I'm trying to use the `find_coefficients` method from `xfoil_module`. But I faced this error :

```
<type 'float'>

Traceback (most recent call last):
  File "C:/Users/PINTO ASU PETHUK/Desktop/TugasAkhir/pinto.py", line 2, in <module>
    find_pressure_coefficients(airfoil='naca0012', Reynolds = 1e6, alpha=12.,NACA=True)
  File "C:/Users/PINTO ASU PETHUK/Desktop/TugasAkhir\xfoil_module.py", line 853, in find_pressure_coefficients
    NACA=NACA, PANE=PANE)
  File "C:/Users/PINTO ASU PETHUK/Desktop/TugasAkhir\xfoil_module.py", line 207, in call
    startupinfo = startupinfo)
  File "C:\Python27\lib\subprocess.py", line 386, in __init__
    errread, errwrite), to_close = self._get_handles(stdin, stdout, stderr)
  File "C:\Python27\lib\subprocess.py", line 536, in _get_handles
    c2pwrite = self._make_inheritable(c2pwrite)
  File "C:\Python27\lib\subprocess.py", line 570, in _make_inheritable
    _subprocess.DUPLICATE_SAME_ACCESS)
OverflowError: long too big to convert
```

Here's my source code :

```
from xfoil_module import find_coefficients
find_coefficients(airfoil='naca0012',alpha=12.)
```

I need it to work for my thesis :(

Thanks!

**Comment by leal26** [comment]
Hello,

I do not have this error on my computer. Could you provide more information regarding your install, OS, and where you are running this? Just from the Error message, I am not able to figure out what the problem is. I am using Python 3.7 on Windows OS.

Thanks,

Pedro

**Comment by pintokoaji** [comment]
Hi,

I'm sorry, but i think that you use Python 2.7 in your programs. And now I have new problem with your print syntax without using "()" after print. 

Thanks!
Pinto
