### ISSUE TITLE
Problem running

### ISSUE THREAD

**Issue by Darius-bit** [leal26/AeroPy#22]
Hi,
I am using Anaconda3 and I installed Aeropy. When I try the sample code:
`from aeropy.xfoil_module import find_coefficients
find_coefficients(airfoil='naca0012', alpha=12.)`
I got this error:
runfile('C:/Users/x/untitled2.py', wdir='C:/Users/x')
Traceback (most recent call last):

  File "C:\Users\x\untitled2.py", line 9, in <module>
    find_coefficients(airfoil='naca0012', alpha=12.)

  File "C:\Users\x\anaconda3\lib\site-packages\aeropy\xfoil_module.py", line 983, in find_coefficients
    call(airfoil, alpha, Reynolds=Reynolds,

  File "C:\Users\x\anaconda3\lib\site-packages\aeropy\xfoil_module.py", line 229, in call
    ps = sp.Popen(['xfoil.exe'],

  File "C:\Users\x\anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py", line 105, in __init__
    super(SubprocessPopen, self).__init__(*args, **kwargs)

  File "C:\Users\x\anaconda3\lib\subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,

  File "C:\Users\x\anaconda3\lib\subprocess.py", line 1307, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,

FileNotFoundError: [WinError 2] Impossibile trovare il file specificato

How can figure it out? 
Best
Dario

**Comment by Skullsploder** [comment]
Hi Darius, I had the same problem. Try adding the Xfoil directory to your system's PATH variable, that fixed it for me.

**Comment by gregshum** [comment]
I have the same problem in this module. Do you remember how did you solve this issue?
